# Generated by Django 6.0.3 on 2026-04-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0004_blockmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockmodel',
            name='blockname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
