# Generated by Django 6.0.3 on 2026-04-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0005_blockmodel_blockname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
