# Generated by Django 6.0.3 on 2026-04-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0006_alter_voter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='voter',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
