# Generated by Django 6.0.3 on 2026-04-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0007_voter_description_voter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='room_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='zone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
