# Generated by Django 6.0.3 on 2026-04-04 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0009_roomtype_style_zone_alter_product_room_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price for 1m')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_at_square',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=10),
        ),
        migrations.AddField(
            model_name='style',
            name='style_kf',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zone',
            name='zone_kf',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voter.room'),
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
