# Generated by Django 6.0.3 on 2026-04-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0010_room_remove_product_price_product_price_at_square_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='base_price',
        ),
    ]
