# Generated by Django 6.0.3 on 2026-04-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0011_remove_room_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockmodel',
            name='products',
        ),
        migrations.AddField(
            model_name='blockmodel',
            name='Room',
            field=models.ManyToManyField(to='voter.room'),
        ),
        migrations.AddField(
            model_name='blockmodel',
            name='style',
            field=models.ManyToManyField(to='voter.style'),
        ),
        migrations.AddField(
            model_name='blockmodel',
            name='zone',
            field=models.ManyToManyField(to='voter.zone'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=101),
        ),
    ]
