# Generated by Django 6.0.3 on 2026-04-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0012_remove_blockmodel_products_blockmodel_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
