# Generated by Django 6.0.3 on 2026-04-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0013_style_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='base_price',
            field=models.IntegerField(default=0),
        ),
    ]
