# Generated by Django 6.0.3 on 2026-04-04 23:48

import django.db.models.deletion
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0014_room_base_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StylePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='style_pictures')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voter.style')),
            ],
        ),
    ]
