# Generated by Django 6.0.3 on 2026-04-04 23:48

import django.db.models.deletion
from django.db import migrations, models

try:
    import easy_thumbnails.fields as thumbnail_fields
except ModuleNotFoundError:
    thumbnail_fields = None


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0014_room_base_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StylePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', (thumbnail_fields.ThumbnailerImageField if thumbnail_fields else models.FileField)(upload_to='style_pictures')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voter.style')),
            ],
        ),
    ]
