# Generated by Django 6.0.3 on 2026-04-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter", "0015_stylepictures"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSettings",
            fields=[
                ("id", models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ("admin_chat_id", models.CharField(blank=True, default="", max_length=64)),
            ],
            options={
                "verbose_name": "Настройки бота",
                "verbose_name_plural": "Настройки бота",
            },
        ),
    ]
