# Generated by Django 6.0.3 on 2026-04-05 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0016_botsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Получатель Telegram',
                'verbose_name_plural': 'Получатели Telegram',
                'ordering': ('-last_seen', 'chat_id'),
            },
        ),
        migrations.AddField(
            model_name='botsettings',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_settings', to='voter.telegramrecipient'),
        ),
    ]
