upstream django_app {
    server web:8000;
}

server {
    listen 80;
    # Здесь можно указать домен или оставить _, чтобы принимать всё
    server_name _;

    # Логи (опционально, но полезно для продакшена)
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location / {
        proxy_pass http://django_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Раздача статических файлов
    location /static/ {
        alias /app/static/;
    }

    # Раздача медиа файлов (загруженных пользователями)
    location /media/ {
        alias /app/media/;
    }
}